project:
  type: website
  output-dir: "docs"

website:
  title: "Anassé Yahanan"
  navbar:
    left: 
      - text: "Accueil"
        file: index.qmd
      - text: "Portfolio"
        file: projets.qmd
      - text: "Mon CV"
        file: cv.qmd
      - text: "Actualités"
        file: news.qmd
      - text: "Contact"
        file: contact.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmos
    css: styles.css



