project:
  type: website
  output-dir: "docs"

website:
  title: "Anassé Yahanan"
  navbar:
    left: 
      - text: "Accueil"
        file: index.qmd
      - text: "Projets"
        file: projets.qmd
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmos
    css: styles.css



